spring.application.name=sequence-generator

spring.datasource.url=jdbc:mysql://localhost:3306/sequence_generator
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8083

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.instance.prefer-ip-address=true