spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:mysql://localhost:3306/banking_app_new?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082
  servlet:
    context-path: /api/transactions
